### ISSUE TITLE
Ban New Armors from Perilous Moons / Add Elder Maul Spec to Allowed Spec Counter

### ISSUE THREAD

**Issue by nitto888** [Box-Of-Hats/runelite-plugin-corp-ffa#18]
TzRek-Chad(MTXP) of Corp FFA07 team -

Elder Maul spec will be allowed in the coming update, if able to add today or must be done on release would be nice to see this added ASAP to avoid plugin chaos on release or not allowing until fixed.

Blood Moon Armour such as Blood Moon chestplate and Blood Moon Tassets do not trigger but are STR bonus not allowed.
Please add to bans. (Eclipse moon, Blood Moon, and Blue Moon sets)

**Comment by nitto888** [comment]
TzRek-Chad(MTXP) of Corp FFA07 team -

Elder Maul spec will be allowed in the coming update, if able to add today or must be done on release would be nice to see this added ASAP to avoid plugin chaos on release or not allowing until fixed.

Blood Moon Armour such as Blood Moon chestplate and Blood Moon Tassets do not trigger but are STR bonus not allowed.
Please add to bans. (Eclipse moon, Blood Moon, and Blue Moon sets)

**Comment by Box-Of-Hats** [comment]
Waiting for release via the plugin hub: https://github.com/runelite/plugin-hub/pull/6113

**Comment by Veracs** [comment]
@Box-Of-Hats Issue merged into runelite:master on June 7, 2024 :)
