### ISSUE TITLE
Add Emberlight as Arclight variant to be counted as a banned weapon

### ISSUE THREAD

**Issue by Veracs** [Box-Of-Hats/runelite-plugin-corp-ffa#21]
As of the release of While Guthix Sleeps, the Emberlight was introduced into the game. This item is an upgrade to the arclight, and its special attack functions the same.

**Comment by Veracs** [comment]
@Box-Of-Hats Do you know if/when Runelite will review and merge your most recent commit, which includes the addition of the Emberlight?

**Comment by Box-Of-Hats** [comment]
@Veracs I've submitted the update to the Runelite team this morning. It usually takes up to a week for them to approve updates.


You can see the progress here: https://github.com/runelite/plugin-hub/pull/6317

**Comment by Box-Of-Hats** [comment]
@Veracs The Runelite devs have just approved this so it should be live and working now 🙂

Thanks again for your work on this issue!
