### ISSUE TITLE
Special Attack is not registering properly on Corp FFA

### ISSUE THREAD

**Issue by FatherTacos** [Box-Of-Hats/runelite-plugin-corp-ffa#23]
I do a lot of Corporeal Beast, and use the Corp FFA plug in. Typically, when you use the plug in, you are able to see your group's specs. This has gone away. You can see the words and the item being used, but it is not registering the spec attacks and keeps the amount at 0.

**Comment by Box-Of-Hats** [comment]
Can you please try again now?

**Comment by FatherTacos** [comment]
Thank you for looking into this, I Just did 100kc's and it did not work.

**Comment by FatherTacos** [comment]
![2024-08-22_09-37-02](https://github.com/user-attachments/assets/0c7478df-e022-4c8d-9e54-8dfef7af3159)

voidwaker spec. not showing up.

**Comment by Box-Of-Hats** [comment]
The voidwaker isn't an allowed spec weapon so it isn't counted. Only the BGS, DWS and arclight (if configured in settings) count
